export const SITE = {
  website: "https://aimaker-lab.com/",
  author: "AI Maker Lab",
  profile: "https://aimaker-lab.com/about/",
  desc: "Vibe Coding（v0 / Lovable / Bolt / Cursor）と AI動画・AI音声・業務自動化を、個人開発者が実際に触って料金・使い勝手・収益化までを書きとめるジャーナル。AI副業ロードマップ、ホスティング、ドメイン選びの実体験レビューも。",
  title: "AI Maker Lab — Vibe Coding と個人開発の実体験ジャーナル",
  ogImage: "aimaker-lab-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 6,
  postPerPage: 8,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit page",
    url: "",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "ja",
  timezone: "Asia/Tokyo",
} as const;
